hilmaf/gamepound

springRepo/gamepound/src/main/java/com/gamepound/app/HomeController.java
springRepo/gamepound/src/main/webapp/WEB-INF/views/home.jsp

* 팀원들에게 따로 전달해야 하는 것
- lib 폴더 생성
- 설정 Template 및 base경로 수정
* 프로젝트 파일 생성

[feat] 프로젝트 생성

---

springRepo/gamepound/pom.xml
springRepo/gamepound/src/main/resources/mybatis/config.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/xxxxx-mapper.xml
springRepo/gamepound/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
springRepo/gamepound/src/main/webapp/WEB-INF/spring/root-context.xml
springRepo/gamepound/src/main/webapp/WEB-INF/web.xml

* pom.xml
* mybatis/config.xml
* mybatis/mapper
* web.xml
* root context.xml
* servlet context.xml

[feat] springTemplate(xml) 공유

---

.gitignore
springRepo/gamepound/src/main/resources/log4j.xml

[feat] log4j.xml 파일 공유

---

springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHJY.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHJY.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHJY.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/vo/MemberVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-mapper.xml
springRepo/gamepound/src/main/webapp/WEB-INF/spring/root-context.xml

- Member Controller, Service, Dao, Vo, mapper파일 추가

[feat] 로그인 기능 추가, loginMember session저장

---

springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/config.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml

1. vo별칭 추가
2. 프로필 사진 변경 기능 구현(DB만 변경, 화면에 변경된 정보 보내는 거 나중에 추가할 예정)

Hyj 1231_01011944

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java

[feat] 후원 기능구현 시작

---

springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectVo.java

[file] projectVo생성

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java

[fix] 버그 주석처리

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/resources/mybatis/mapper/back-mapper.xml

* 기능 구현: 후원하기, 후원완료 결과페이지, 후원취소

[feat] 기능 추가

---

springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectVo.java
springRepo/gamepound/src/main/resources/mybatis/config.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. config에 projectVo, backVo별칭 추가
2. projectVo작성
3. project-mapper에 select문 추가
4. 프로필 이름 변경 기능 구현

Hyj 01021453_01021654

---

springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml

1. 소개 변경 구현
2. 웹사이트 변경 구현
3. 비밀번호 변경 구현

Hyj 01022023_01030109

---

springRepo/gamepound/src/main/java/com/gamepound/app/review/controller/ReviewControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/dao/ReviewDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/service/ReviewServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/vo/ReviewStatVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/vo/ReviewVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java

* 파일생성
* vo 코드 작성
* 리뷰 목록 조회 기능 구현 중

Lgm0103 01

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/controller/ReviewControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/dao/ReviewDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/service/ReviewServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/vo/ReviewVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/review-mapper.xml

* vo 달성률계산 메소드 삭제
* 기능추가: 리뷰 작성
* 자잘수정

Lgm0103 02

---

reactRepo/gamepound/.gitignore
reactRepo/gamepound/README.md
reactRepo/gamepound/package-lock.json
reactRepo/gamepound/package.json
reactRepo/gamepound/public/index.html
reactRepo/gamepound/public/manifest.json
reactRepo/gamepound/public/robots.txt
reactRepo/gamepound/src/App.css
reactRepo/gamepound/src/App.js
reactRepo/gamepound/src/index.css
reactRepo/gamepound/src/index.js
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/ProjectRemainingPeriod.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/dao/ReviewDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/service/ReviewServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/review-mapper.xml

* 마감기한 계산하는 기능 추가
* 리뷰 목록 및 통계 조회 기능 추가
* reactRepo 프로젝트 생성
* 그 외 자잘 수정

이경민_0103_03

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackDetailVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/back-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/review-mapper.xml

* 후원하기(화면)
* vo 수정
* 후원 상세 조회 기능 구현 중
* 날짜 포맷 쿼리 수정(후기)

Lgm0104 01

---

springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceLKM.java

이경민 240104_03

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackDetailVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/controller/PaymentControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/dao/PaymentDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/service/PaymentServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/vo/PaymentVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/back-mapper.xml

* 기능 수정(후원취소, 후원)
* 파일 추가(payment)

이경민_0105_01

---

reactRepo/gamepound/package-lock.json
reactRepo/gamepound/package.json
reactRepo/gamepound/src/App.js
reactRepo/gamepound/src/App.jsx
reactRepo/gamepound/src/component/common/Wrap.jsx
reactRepo/gamepound/src/component/common/footer/Footer.jsx
reactRepo/gamepound/src/component/common/header/Header.jsx
reactRepo/gamepound/src/component/common/main/Main.jsx
reactRepo/gamepound/src/component/project/ProjectBoxInfo.jsx
reactRepo/gamepound/src/component/project/ProjectBriefInfo.jsx
reactRepo/gamepound/src/pages/backingpage/BackMain.jsx
reactRepo/gamepound/src/pages/backingpage/BackingDetails.jsx
reactRepo/gamepound/src/pages/backingpage/BackingProcess.jsx
reactRepo/gamepound/src/pages/backingpage/PaymentCheck.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/PaymentRequest.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/controller/PaymentControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/dao/PaymentDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/service/PaymentServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/payment/vo/PaymentVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/back-mapper.xml

* 백엔드 기능: 후원 내용 변경
* 리액트 협업 위한 기본 폴더 구조 및 파일 생성
* 백엔드 결제 기능 구현 고민 중 - 아마 리액트랑 병행될 것 같음

이경민_0106_01

---

springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectDetailControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectCommunityVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/project-list-mapper.xml

상세조회 - 계획, 업데이트, 커뮤니티
공개예정 상세조회 - 계획, 업데이트

[feat] 프로젝트 상세조회 기능 구현

---

reactRepo/gamepound/src/component/common/footer/Footer.jsx
reactRepo/gamepound/src/component/project/ProjectBoxInfo.jsx
reactRepo/gamepound/src/component/project/ProjectBriefInfo.jsx
reactRepo/gamepound/src/component/userpage/ProfileArea.jsx
reactRepo/gamepound/src/component/userpage/ProfileMenu.jsx
reactRepo/gamepound/src/component/userpage/ProfileNav.jsx
reactRepo/gamepound/src/pages/backingpage/BackCanceled.jsx
reactRepo/gamepound/src/pages/backingpage/BackCompleted.jsx
reactRepo/gamepound/src/pages/backingpage/BackDetail.jsx
reactRepo/gamepound/src/pages/backingpage/BackInfo.jsx
reactRepo/gamepound/src/pages/backingpage/BackMain.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
reactRepo/gamepound/src/pages/userpage/UserPageMain.jsx
reactRepo/gamepound/src/pages/userpage/UserReview.jsx

* UserPage 리액트 작업
* 공통 component ProjectBriefInfo, ProjectBoxInfo 작업
* 후원 상세 조회, 후원 페이지 리액트 작업

이경민0108_01

---

reactRepo/gamepound/public/index.html
reactRepo/gamepound/src/component/common/Wrap.jsx
reactRepo/gamepound/src/component/project/ProjectBriefInfo.jsx
reactRepo/gamepound/src/pages/backingpage/BackingForm.jsx
reactRepo/gamepound/src/pages/backingpage/BackingProcess.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectBriefVo.java
springRepo/gamepound/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

* react 설정
* CORS 설정
* 후원하기 화면 fetch 통신 작업 중

이경민_0108_02

---

reactRepo/gamepound/src/component/back/BackBriefInfo.jsx
reactRepo/gamepound/src/component/project/ProjectBoxInfo.jsx
reactRepo/gamepound/src/component/userpage/ProfileArea.jsx
reactRepo/gamepound/src/component/userpage/ProfileNav.jsx
reactRepo/gamepound/src/pages/userpage/ReviewBox.jsx
reactRepo/gamepound/src/pages/userpage/ReviewList.jsx
reactRepo/gamepound/src/pages/userpage/ReviewStats.jsx
reactRepo/gamepound/src/pages/userpage/ReviewWrite.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
reactRepo/gamepound/src/pages/userpage/UserPageMain.jsx
reactRepo/gamepound/src/pages/userpage/UserReview.jsx

* 공통 컴포넌트 BackBriefInfo, ProjectBoxInfo css 수정
* userPage 화면 작업 중

이경민_0109_03

---

reactRepo/gamepound/src/component/back/BackBriefInfo.jsx
reactRepo/gamepound/src/component/common/main/Main.jsx
reactRepo/gamepound/src/component/context/BackingContext.jsx
reactRepo/gamepound/src/component/userpage/ProfileArea.jsx
reactRepo/gamepound/src/pages/backingpage/backing/BackingDetails.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
reactRepo/gamepound/src/pages/userpage/UserPageMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackDetailVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/BackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/review/vo/ReviewVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

* BackingContext상의 로직 이슈 발견
* 페이지마다 로그인 유효성 체크 작업 중
* 공통 component props 처리 완료
* fetch: 내 후원 목록 조회

이경민0112_01

---

reactRepo/gamepound/src/component/common/main/Main.jsx
reactRepo/gamepound/src/pages/projectpage/ProjectMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/CommunityPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/DetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchDetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchUpdatePage.jsx

HYJ_01122346_01132238

---

reactRepo/gamepound/src/pages/projectpage/detail/CommunityPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/DetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchDetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/list/CategoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ImminentPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/NewPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PopularPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PrelaunchPage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java

Hyj 01140259

---

reactRepo/gamepound/src/component/common/header/nav/Nav.jsx
reactRepo/gamepound/src/component/project/ProjectListBoxInfo.jsx
reactRepo/gamepound/src/pages/projectpage/list/CategoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ImminentPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ListMain.jsx
reactRepo/gamepound/src/pages/projectpage/list/NewPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PopularPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PrelaunchPage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. Link 주소 변경
2. 카테고리 목록 조회 fetch
3. 목록조회 css변경

HYJ_01150914_01151741

---

springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java

[fix] import 오류 수정

---

reactRepo/gamepound/src/component/project/ProjectListBoxInfo.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchDetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/list/CategoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ImminentPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/NewPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PopularPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PrelaunchPage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectDetailControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. 필요없는  syso, 주석, log 삭제
2. 목록 조회 기본 페이지 완성

HYJ_01152209_01160113

---

reactRepo/gamepound/src/pages/backingpage/backing/PaymentCheck.jsx
reactRepo/gamepound/src/pages/projectpage/search/ProjectSearch.jsx
reactRepo/gamepound/src/pages/userpage/ReviewWrite.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java

* 기능 구현 중: 프로젝트 검색, 후원하기, 리뷰 파일 업로드

이경민0116_01

---

reactRepo/gamepound/src/component/project/ProjectListBoxInfo.jsx
reactRepo/gamepound/src/pages/projectpage/list/CategoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ImminentPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/NewPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PopularPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PrelaunchPage.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSetting.jsx

1. 프로젝트박스 CSS
2. 목록 조회 CSS
3. 프로필 세팅 화면 생성

HYJ_01161753_01162010

---

reactRepo/gamepound/src/pages/settingPage/ProfileSetting.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java

1. 프로필 설정 회원탈퇴 버튼에 경로 추가
2. 설정 백단이랑 연결 중

HYJ_01162257_01170127

---

reactRepo/gamepound/src/component/back/BackBriefInfo.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

이경민0117_01

---

reactRepo/gamepound/package-lock.json
reactRepo/gamepound/src/component/back/BackBriefInfo.jsx

[chore] 오류 수정

---

reactRepo/gamepound/src/component/common/header/LoginArea.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSetting.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml

1. 헤더 프로필에 경로 추가
2.  설정화면 기초 fetch

HYJ_01171048_01171752

---

reactRepo/gamepound/src/component/back/BackBriefInfo.jsx
reactRepo/gamepound/src/pages/backingpage/backing/PaymentCheck.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
reactRepo/gamepound/src/pages/userpage/UserReview.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java

* 후원 실패 목록 조회 오류 수정
* 기타 오류 수정 중

이경민0118 01

---

reactRepo/gamepound/src/component/common/header/Header.jsx
reactRepo/gamepound/src/component/common/header/LoginArea.jsx
reactRepo/gamepound/src/component/common/main/Main.jsx
reactRepo/gamepound/src/component/context/SearchContext.jsx
reactRepo/gamepound/src/component/project/ProjectBoxInfo.jsx
reactRepo/gamepound/src/component/search/Condition.jsx
reactRepo/gamepound/src/pages/backingpage/backing/PaymentCheck.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java

* 이미지 경로 수정
* 불필요한 요소 삭제 및 공통 컴포넌트 css 수정
* 오류 수정: 후원하기 customerUid 안 담기는 문제 해결 완료

이경민0118 04

---

.gitignore
reactRepo/gamepound/src/pages/userpage/ReviewStats.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
reactRepo/gamepound/src/pages/userpage/UserProfile.jsx
reactRepo/gamepound/src/pages/userpage/UserReview.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/java/com/gamepound/app/util/DataProcessingUtil.java

* 유저페이지 경로 수정에 따른 변수 수정
* css 수정
* 올린 프로젝트 null 체크 진행중
* 깃이그노어 파일 수정

이경민0119 02

---

reactRepo/gamepound/src/component/context/SearchContext.jsx
reactRepo/gamepound/src/component/context/UserPageContext.jsx
reactRepo/gamepound/src/component/search/Condition.jsx
reactRepo/gamepound/src/component/userpage/ProfileArea.jsx
reactRepo/gamepound/src/pages/backingpage/PaymentChangeModal.jsx
reactRepo/gamepound/src/pages/backingpage/RewardChangeModal.jsx
reactRepo/gamepound/src/pages/projectpage/search/SearchMain.jsx
reactRepo/gamepound/src/pages/userpage/ReviewBox.jsx
reactRepo/gamepound/src/pages/userpage/ReviewList.jsx
reactRepo/gamepound/src/pages/userpage/ReviewStats.jsx
reactRepo/gamepound/src/pages/userpage/UserPageMain.jsx
reactRepo/gamepound/src/pages/userpage/UserReview.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/page/vo/PageVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectListVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/search-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

* 조건검색 작업 중
* 모달 페이지 파일 생성
* 페이징 처리 위한 리팩토링

이경민0119 04

---

reactRepo/gamepound/src/component/common/header/Header.jsx
reactRepo/gamepound/src/component/common/header/LoginArea.jsx
reactRepo/gamepound/src/component/context/SearchContext.jsx
reactRepo/gamepound/src/component/project/ProjectBoxInfo.jsx
reactRepo/gamepound/src/component/search/Condition.jsx
reactRepo/gamepound/src/pages/backingpage/BackInfo.jsx
reactRepo/gamepound/src/pages/backingpage/PaymentChangeModal.jsx
reactRepo/gamepound/src/pages/backingpage/RewardChangeModal.jsx
reactRepo/gamepound/src/pages/projectpage/search/ProjectSearch.jsx
reactRepo/gamepound/src/pages/projectpage/search/SearchMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectBriefVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/search-mapper.xml

* 조건 검색 구현 완료
* css 클래스 명칭 수정
* 모달창 화면 작업 중

이경민0120 01

---

reactRepo/gamepound/src/pages/settingPage/NameSetting.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSettingMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java

HYJ_01192046

---

reactRepo/gamepound/src/component/search/Condition.jsx

이경민0120_02

---

reactRepo/gamepound/package-lock.json
reactRepo/gamepound/package.json
reactRepo/gamepound/src/component/common/footer/Footer.jsx
reactRepo/gamepound/src/component/common/main/Main.jsx
reactRepo/gamepound/src/pages/backingpage/BackDetail.jsx
reactRepo/gamepound/src/pages/backingpage/BackInfo.jsx
reactRepo/gamepound/src/pages/backingpage/PaymentChangeModal.jsx
reactRepo/gamepound/src/pages/backingpage/RewardChangeModal.jsx
reactRepo/gamepound/src/pages/mainpage/MainPage.jsx

* 메인 화면 푸터 화면 구현
* 후원내용 변경 모달 작업 중
* 라이브러리: react modal

이경민0121 02

---

reactRepo/gamepound/package-lock.json
reactRepo/gamepound/package.json
reactRepo/gamepound/src/admin/component/main/AdminMain.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/component/context/UserPageContext.jsx
reactRepo/gamepound/src/pages/backingpage/BackInfo.jsx
reactRepo/gamepound/src/pages/backingpage/PaymentChangeModal.jsx
reactRepo/gamepound/src/pages/userpage/ReviewList.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

* 페이지네이션 라이브러리 추가
* 관리자 프로젝트 페이지 준비
* 리뷰 페이지네이션 구현 완료
* 모달창 띄우기 완료
* 새로고침하면 profileVo 리셋되는 현상 수정 중

이경민0122_01

---

reactRepo/gamepound/src/component/common/footer/Footer.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSettingMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml

1. 프로필 설정 이름, 소개, 웹사이트, 비밀번호 변경 기능 추가 사진변경 기능 구현 중
2. footer 가로 길이 수정

HYJ_01221002_01221741

---

reactRepo/gamepound/src/pages/settingPage/ProfileSettingMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java

HYJ_01222047_01230228

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/AdminProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/AdminProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/AdminProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectSearchVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-project-mapper.xml

* 어드민 백엔드 기능 구현 완료
* 프로젝트 목록 조회 css 참고

이경민0123 01

---

springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/AdminMemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/AdminMemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/AdminMemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-member-mapper.xml

HYJ_01231014_01231749

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/component/back/BackBriefInfo.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/AdminProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/AdminProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/AdminProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectSearchVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/dao/UserPageDao.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/java/com/gamepound/app/util/DataProcessingUtil.java
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

* 프로젝트 관리 화면 디자인 완료
* loginMemberVo 일치여부에 따른 작업 중
* 프로젝트 관리 fetch 작업 중

이경민0123 02

---

reactRepo/gamepound/src/admin/component/common/Aside.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/AdminBackControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/AdminBackDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/AdminBackServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/AdminBackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/AdminMemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/AdminMemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/AdminMemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-back-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-member-mapper.xml

1. 관리자 페이지 백단 구현
2. 사이드바 이름 수정

HYJ_01232110_01240238

---

reactRepo/gamepound/src/admin/component/main/AdminMain.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/AdminProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/AdminProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/AdminProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectDetailVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-project-mapper.xml

* 프로젝트 상세 조회 데이터 띄우기
* 프로젝트 목록 조회 데이터 띄우기
* 같다 표기 수정

이경민0124 01

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/component/userpage/ProfileArea.jsx
reactRepo/gamepound/src/pages/userpage/UserCreated.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/AdminProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/AdminProjectDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/AdminProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectSearchVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-project-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml

* 어드민 프로젝트 관리 기능 구현 완료
* 계정관리 navigate 코드 추가
* 로그인 유저와 유저페이지 유저 일치여부에 따른 데이터 조회 변화

이경민0124 02

---

reactRepo/gamepound/src/admin/component/main/AdminMain.jsx
reactRepo/gamepound/src/admin/pages/backer/BackerMain.jsx
reactRepo/gamepound/src/admin/pages/user/UserDetail.jsx
reactRepo/gamepound/src/admin/pages/user/UserMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/vo/AdminBackVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/AdminMemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/AdminMemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/AdminMemberServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/vo/MemberVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-back-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-member-mapper.xml

1. mapper id 중복오류 수정
2. 사용자 관리 화면 구현
3. 사용자관리 상세페이지 주소 추가
4. 후원자 관리 페이지 만드는중

HYJ_01240933_01241744

---

reactRepo/gamepound/src/admin/pages/user/UserDetail.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/AdminMemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java

1. 비밀번호 변경 오류 수정
2. 사용자 상세 페이지 구현

HYJ_01242208_01250331

---

reactRepo/gamepound/src/component/payment/EnrollCard.jsx
reactRepo/gamepound/src/pages/backingpage/BackCanceled.jsx
reactRepo/gamepound/src/pages/backingpage/backing/PaymentCheck.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/controller/BackControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/filter/EncodingFilter.java
springRepo/gamepound/src/main/java/com/gamepound/app/interceptor/LoginInterceptor.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
springRepo/gamepound/src/test/java/com/gamepound/app/UserTestClass.java

* 필터, 인터셉터 추가
* 코드 정리
* 테스트 파일 생성

이경민 0125 02

---

reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/component/context/UserPageContext.jsx
reactRepo/gamepound/src/pages/backingpage/BackCanceled.jsx
reactRepo/gamepound/src/pages/userpage/ReviewBox.jsx
reactRepo/gamepound/src/pages/userpage/ReviewWrite.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/filter/EncodingFilter.java
springRepo/gamepound/src/main/java/com/gamepound/app/interceptor/LoginInterceptor.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/AdminProjectControllerLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/AdminProjectServiceLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/controller/UserPageController.java
springRepo/gamepound/src/main/java/com/gamepound/app/userpage/service/UserPageService.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-project-mapper.xml

* 리뷰 조회 수정 중
* 프로젝트 검색 쿼리문 수정
* 필터 및 인터셉터 작업 중

이경민0126 01

---

reactRepo/gamepound/src/pages/projectpage/detail/CommunityPage.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSettingMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectDetailControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/vo/ProjectDetailCntVo.java
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. 프로젝트 상세페이지 커뮤니티 게시글, 댓글 작성 구현
2. 프로젝트 상세페이지 관련 VO생성

HYJ_01260918_01261747

---

reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/pages/userpage/ReviewBox.jsx
springRepo/gamepound/pom.xml
springRepo/gamepound/src/main/java/com/gamepound/app/interceptor/LoginInterceptor.java
springRepo/gamepound/src/main/resources/mybatis/mapper/userpage-mapper.xml
springRepo/gamepound/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
springRepo/gamepound/src/test/java/com/gamepound/back/app/BackingProcessTest.java

* 리뷰 조회 이미지 안뜨는 문제 해결
* 테스트 코드 파일 준비
* 어드민 페이지 로그인 체크 인터셉터 구현 완료
* dependency 추가 : 제이유닛, 스프링 test, 스프링 batch

이경민0126 02

---

reactRepo/gamepound/src/pages/projectpage/detail/CommunityPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/DetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchDetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchUpdatePage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdateCreatePage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdatePage.jsx
reactRepo/gamepound/src/pages/projectpage/list/CategoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/ImminentPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/NewPage.jsx
reactRepo/gamepound/src/pages/projectpage/list/PopularPage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/dao/MemberDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectDetailControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. 프로젝트 상세페이지
- 네비바에 업데이트, 커뮤니티 게시글 수 추가
- 창작자 댓글 구형
- 프로젝트 업데이트 작성 페이지 구현
- 리워드 안 나오던 오류 수정
2. 프로젝트 리스트
- 프로젝트 상태, 달성률로 조회
3. 설정변경 후 세션에 저장 구현 중

Hyj 01272255

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/admin/pages/project/ProjectMain.jsx
reactRepo/gamepound/src/component/common/footer/Footer.jsx
reactRepo/gamepound/src/component/project/ProjectBriefInfo.jsx
reactRepo/gamepound/src/component/search/Condition.jsx
reactRepo/gamepound/src/pages/backingpage/BackInfo.jsx
reactRepo/gamepound/src/pages/userpage/ReviewBox.jsx
reactRepo/gamepound/src/pages/userpage/ReviewList.jsx
reactRepo/gamepound/src/pages/userpage/ReviewStats.jsx
reactRepo/gamepound/src/pages/userpage/UserBacked.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java

* 수정사항 테스트 문서 반영중
* 불필요한 주석 및 import 삭제

이경민0130 02

---

reactRepo/gamepound/src/admin/pages/backer/BackerMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/CommunityPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/DetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchUpdatePage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdatePage.jsx
reactRepo/gamepound/src/pages/settingPage/ProfileSettingMain.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/controller/MemberControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/member/service/MemberServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/member-settings-mapper.xml

1. 프로젝트 상세 페이지
- CSS수정
- 본인 프로젝트 선물 선택 불가능 기능 추가
2. 회원정보 수정 후 세션에 변경된 정보 저장

HYJ_01301016_01301550

---

reactRepo/gamepound/src/pages/projectpage/detail/DetailMain.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdateCreatePage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdatePage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/member/vo/MemberVo.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/controller/ProjectDetailControllerHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoHYJ.java
springRepo/gamepound/src/main/java/com/gamepound/app/project/service/ProjectServiceHYJ.java
springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

1. 프로젝트상세
- 후원기록이 있을 시 후원 기능 막음

HYJ_01301925_01310038

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
reactRepo/gamepound/src/component/context/UserPageContext.jsx
reactRepo/gamepound/src/component/userpage/ProfileNav.jsx

이경민0131 02

---

reactRepo/gamepound/src/admin/pages/project/ProjectDetail.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/util/DataProcessingUtil.java

이경민0131_03

---

reactRepo/gamepound/src/pages/projectpage/detail/PrelaunchStoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/StoryPage.jsx
reactRepo/gamepound/src/pages/projectpage/detail/UpdatePage.jsx
springRepo/gamepound/src/main/java/com/gamepound/app/project/dao/ProjectDaoHYJ.java

HYJ_01311245_01311337

---

springRepo/gamepound/src/main/java/com/gamepound/app/back/dao/BackDaoLKM.java
springRepo/gamepound/src/main/java/com/gamepound/app/back/service/BackServiceLKM.java
springRepo/gamepound/src/main/resources/mybatis/mapper/admin-project-mapper.xml
springRepo/gamepound/src/main/resources/mybatis/mapper/back-mapper.xml

* 후원 시 모인금액 증가
* 어드민 프로젝트 관리 OK_YN, OK_DATE 업데이트 쿼리 추가

이경민0131 04

---

springRepo/gamepound/src/main/resources/mybatis/mapper/project-mapper.xml

HYJ_01312235
